### ISSUE TITLE
Serialization of directed vs undirected relationships

### ISSUE THREAD

**Issue by dlschwartz** [srophe/spear#13]
@wsalesky the TEI uses @mutual for an undirected or bi-directional relationship like "spouseOf" and @active/@passive for a directed relationship "employerOf".  RDF is only directed. As a result, when we have tei:relation/@mutual we need to generate two direct properties/statement instances. However, when we have tei:relation/@active and /@passive we don't need to generate relationships going the other way. 

See 3036-10. The last 9 lines indicate that each recipient sent a letter to Severus when they did not.

**Comment by wsalesky** [comment]
Note to selfL example records for mutual relationship: 10510-36
